"use client";

import { useState } from "react";
import { AppSidebar } from "../components/AppShell";
import "./comparer.css";

const creators = [
  { rank:1,name:"Hafsa Achraf",image:"/explorer/maya.png",tier:"Lifestyle · Méga",city:"Casablanca, Maroc",followers:"1.4M",engagement:"5.2%",views:"620K",score:92,match:"Excellent match",age:"25 – 34 ans",gender:"78% Femmes",countries:"Maroc (62%), France (12%), Algérie (6%)",platforms:["instagram","tiktok","youtube"],categories:"Lifestyle, Beauty, Fashion",quality:"Excellente",brand:"5.0 / 5",budget:"22 000 MAD",coverage:"2.6M – 3.2M",range:"4.8% – 6.0%",video:"150K – 220K",strengths:["Forte affinité avec les parents jeunes","Contenu authentique et storytelling","Excellente répartition géographique"],watch:"Tarifs plus élevés (niveau méga)"},
  { rank:2,name:"Amine HLS",image:"/explorer/amine.png",tier:"Family · Méga",city:"Marrakech, Maroc",followers:"717K",engagement:"4.7%",views:"1.2M",score:89,match:"Très bon match",age:"24 – 35 ans",gender:"72% Femmes / 28% Hommes",countries:"Maroc (71%), France (9%), Espagne (4%)",platforms:["instagram","tiktok","youtube"],categories:"Family, Lifestyle, Travel",quality:"Très bonne",brand:"4.5 / 5",budget:"21 000 MAD",coverage:"2.3M – 2.9M",range:"4.2% – 5.2%",video:"180K – 220K",strengths:["Audience familiale et engagée","Contenu divertissant et relatable","Excellente performance sur TikTok"],watch:"Audience légèrement moins féminine"},
  { rank:3,name:"Sofia HLS",image:"/explorer/sarah.png",tier:"Family · Méga",city:"Marrakech, Maroc",followers:"667K",engagement:"4.5%",views:"980K",score:88,match:"Très bon match",age:"24 – 34 ans",gender:"75% Femmes / 25% Hommes",countries:"Maroc (70%), France (10%), Algérie (5%)",platforms:["instagram","tiktok","youtube"],categories:"Family, Lifestyle",quality:"Très bonne",brand:"4.5 / 5",budget:"21 000 MAD",coverage:"2.0M – 2.7M",range:"4.0% – 5.0%",video:"160K – 220K",strengths:["Contenu familial chaleureux","Bonne proximité avec la communauté","Stories très performantes"],watch:"Moins de diversité géographique"},
  { rank:4,name:"Souhaila Abbad",image:"/explorer/salma.png",tier:"Lifestyle · Macro",city:"Kénitra, Maroc",followers:"176K",engagement:"6.1%",views:"92K",score:86,match:"Bon match",age:"22 – 32 ans",gender:"85% Femmes",countries:"Maroc (87%), France (6%), Espagne (3%)",platforms:["instagram","tiktok"],categories:"Lifestyle, Beauty, Education",quality:"Bonne",brand:"4.0 / 5",budget:"15 000 MAD",coverage:"900K – 1.2M",range:"5.5% – 7.0%",video:"70K – 120K",strengths:["Très fort taux d’engagement","Tarif accessible","Audience locale très fidèle"],watch:"Portée plus limitée (niveau macro)"},
] as const;

function Social({platform}:{platform:string}){return <i className={`compare-social ${platform}`}>{platform==="instagram"?"◎":platform==="tiktok"?"♪":"▶"}</i>}
function Score({value}:{value:number}){return <span className="compare-score"><strong>{value}</strong></span>}

export default function CompareInfluencersPage(){
  const [selected,setSelected]=useState(creators.map(creator=>creator.name));
  const [saved,setSaved]=useState(false);
  const [favorites,setFavorites]=useState(false);
  const [campaignAdded,setCampaignAdded]=useState(false);
  const activeCreators=creators.filter(creator=>selected.includes(creator.name));
  return <main className="dashboard-page compare-page"><AppSidebar active="explorer"/><section className="dashboard-main compare-main">
    <header className="compare-header"><div><h1>Comparer les influenceurs</h1><p>Comparez jusqu’à 4 créateurs pour trouver les meilleurs matchs pour votre campagne.</p></div><div><button type="button" className={saved?"saved":""} onClick={()=>setSaved(true)}>▯&nbsp; {saved?"Comparaison enregistrée ✓":"Enregistrer la comparaison"}</button><a href="/explorer" aria-label="Fermer">×</a></div></header>
    <section className="compare-topbar"><div><h2>Créateurs sélectionnés ({activeCreators.length}/4)</h2><nav>{activeCreators.map(creator=><button type="button" key={creator.name} onClick={()=>setSelected(current=>current.filter(name=>name!==creator.name))}><img src={creator.image} alt=""/><strong>{creator.name}</strong><span>×</span></button>)}<button type="button" className="compare-add" onClick={()=>setSelected(creators.map(creator=>creator.name))}>＋&nbsp; Ajouter</button></nav></div><aside><h2>Contexte de la campagne</h2><span>“Back to School 2026</span><button type="button">Modifier</button></aside></section>
    <div className="compare-layout"><section className="comparison-table"><aside className="criteria-column"><h2>Critères clés</h2>{["♙ Profil","♧ Followers|(Niveau)","♧ Engagement moyen","♙ Vues moyennes|(par Reel / TikTok)","◎ somatch Score|(pertinence)","♧ Audience|Âge moyen|Genre|Top pays / villes","◫ Plateformes","⬡ Catégories","♢ Qualité de l’audience","♡ Brand Fit","▣ Budget estimé|(par collaboration)","◉ Performances estimées|(pour cette campagne)","♢ Forces principales","♡ Points de vigilance"].map(item=><div key={item}>{item.split("|").map((line,index)=>index===0?<strong key={line}>{line}</strong>:<small key={line}>{line}</small>)}</div>)}</aside>
      {activeCreators.map(creator=><article className="compare-creator-column" key={creator.name}><header><b>{creator.rank}</b><img src={creator.image} alt={creator.name}/><span><h2>{creator.name} <i>◆</i></h2><p>{creator.tier}</p><small>{creator.city}</small></span></header><div className="compare-basic"><strong>♧&nbsp; {creator.followers}</strong><small>{creator.tier.split(" · ")[1]}</small></div><div className="compare-engagement"><strong>♧&nbsp; {creator.engagement}</strong><em>{creator.engagement>"5"?"Très élevé":"Élevé"}</em></div><div className="compare-views"><Social platform="instagram"/><strong>{creator.views}</strong><small>Reel Instagram</small></div><div className="compare-match"><Score value={creator.score}/><strong>{creator.match}</strong></div><div className="compare-audience"><strong>{creator.age}</strong><span>{creator.gender}</span><small>{creator.countries}</small></div><div className="compare-platforms">{creator.platforms.map(platform=><span key={platform}><Social platform={platform}/>{platform}</span>)}</div><div className="compare-categories">{creator.categories}</div><div className="compare-quality">♢ <span>{creator.quality}<small>Authentique</small></span></div><div className="compare-brand">★ ★ ★ ★ ☆ <span>{creator.brand}</span></div><div className="compare-budget"><strong>{creator.budget}</strong><small>par collaboration</small></div><div className="compare-performance"><span>◉<strong>{creator.coverage}</strong><small>couverture</small></span><span>♡<strong>{creator.range}</strong><small>engagement</small></span><span>▷<strong>{creator.video}</strong><small>vues</small></span></div><ul className="compare-strengths">{creator.strengths.map(strength=><li key={strength}>{strength}</li>)}</ul><p className="compare-watch">♧&nbsp; {creator.watch}</p></article>)}</section>
      <aside className="compare-recommendations"><section><h2>✣&nbsp; somatch AI – Recommandation</h2><div className="best-match"><small>Meilleur match global</small><span><img src={creators[0].image} alt="Hafsa Achraf"/><strong>Hafsa Achraf</strong><Score value={92}/></span><p>Le meilleur équilibre entre portée, engagement et adéquation avec votre cible. Parfait pour donner de la visibilité à votre campagne.</p></div><hr/><h3>Combinaison recommandée</h3><p>Associez ces profils pour maximiser vos résultats :</p><div className="recommended-list">{creators.map(creator=><article key={creator.name}><b>{creator.rank}</b><img src={creator.image} alt=""/><span><strong>{creator.name}</strong><small>{creator.tier.split(" · ")[1]}</small></span><Score value={creator.score}/></article>)}</div><hr/><p>Cette combinaison vous permettrait d’atteindre :</p><div className="recommend-metrics"><span>◉<strong>3.8M – 4.9M</strong><small>Couverture estimée</small></span><span>♡<strong>5.0% – 6.2%</strong><small>Engagement moyen</small></span><span>▷<strong>280K – 420K</strong><small>Vues estimées</small></span><span>♧<strong>8K – 12K</strong><small>Participants concours</small></span></div></section><section className="compare-actions-card"><h2>Actions</h2><button type="button" onClick={()=>setCampaignAdded(true)}>＋&nbsp; {campaignAdded?"Ajoutés à la campagne ✓":"Ajouter tous à une campagne"}</button><button type="button" onClick={()=>setFavorites(true)}>▯&nbsp; {favorites?"Ajoutés aux favoris ✓":"Ajouter aux favoris"}</button><button type="button">⇩&nbsp; Exporter la comparaison</button></section></aside></div>
    <footer className="compare-footer"><a href="/favoris">←&nbsp; Retour à la sélection</a><p>✣&nbsp; Les estimations sont indicatives et peuvent varier en fonction du contenu et du timing.</p><button type="button" onClick={()=>setCampaignAdded(true)}>{campaignAdded?"Ajoutés à la campagne ✓":"Ajouter à une campagne　→"}</button></footer>
  </section></main>
}
